name: Daily Commit

on:
  schedule:
    - cron: "30 16 * * *"  # runs daily at 04:30 UTC (adjust as needed)
  workflow_dispatch:  # allows manual trigger

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Add timestamp comment – 24f1002255@ds.study.iitm.ac.in
        run: |
          echo "# Run at $(date -u)" >> daily-log.txt

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit at $(date -u)" || echo "Nothing to commit"
          git push
