name: Daily Commit

on:
  schedule:
    - cron: "30 16 * * *"  # 10:00 PM IST = 16:30 UTC
  workflow_dispatch:

permissions:
  contents: write  # Allow git push using GITHUB_TOKEN

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Add timestamp – 24f1002255@ds.study.iitm.ac.in
        run: |
          echo "# Run at $(date -u)" >> daily-log.txt

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit at $(date -u)" || echo "Nothing to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
